name = "Pony0n RPG"
author = "Pony0n"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b06e244f13fd7be0b8ad06af5448a3be7aeb0508a3156ee8fc0e1df17b48d58"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
