name = "Pony0n RPG"
author = "Pony0n"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e582bc6bcfe74a99691cd769dfc208c542079f94cf165ec5831614e8d3c90e0"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
