import { T, R } from "../../quest-dsl.mjs";

// Capítulo 5 — La era tecnológica (niveles 40–50, ~14 000 XP repartidos)
export default {
  key: "tecnologia", order: 5, group: "campana", icon: "mekanism:steel_casing",
  title: "5. La era tecnológica",
  sub: "Electricidad, máquinas de proceso y redes de almacenamiento.",
  quests: [
    { k: "energia", t: "La era de la energía", sub: "Contexto", deps: ["create.cierre"],
      d: ["Después de la fuerza mecánica llega la electricidad. Usaremos FE (Forge Energy) y tres familias de mods:",
          "&6Create Crafts & Additions&r: convierte la fuerza de Create en electricidad. &6Powah&r: generadores y baterías intermedias. &6Mekanism&r: procesamiento y energía densa. &6AE2&r: almacenamiento y autocrafteo."],
      tasks: [T.check()], rewards: [R.skill(800), R.coins({ esmeralda: 4 })] },

    { k: "alternador", t: "Alternador y motor", sub: "De fuerza a electricidad", deps: ["energia"],
      d: ["El alternador convierte fuerza rotatoria en electricidad. El motor eléctrico hace lo contrario: convierte electricidad en fuerza."],
      tasks: [T.item("createaddition:alternator"), T.item("createaddition:electric_motor")],
      rewards: [R.skill(900), R.item("createaddition:copper_wire", 16)] },
    { k: "cables", t: "Cables y conectores", sub: "Transporte de energía", deps: ["alternador"],
      d: ["Los conectores unen máquinas con cable. Cuidado con la distancia y con la pérdida por hilo fino."],
      tasks: [T.item("createaddition:connector", 4), T.item("createaddition:copper_spool", 2)],
      rewards: [R.skill(900), R.item("createaddition:capacitor")] },
    { k: "molino_rodillo", t: "Laminador (opcional)", sub: "Hilos y varillas", deps: ["cables"], opt: true,
      d: ["El laminador convierte placas en varillas y cables de distintos metales."],
      tasks: [T.item("createaddition:rolling_mill")], rewards: [R.skill(800)] },

    { k: "powah1", t: "Energía intermedia", sub: "Powah", deps: ["energia"],
      d: ["Powah añade generadores sencillos: el furnator quema combustible y el magmator usa lava.", "Guarda la energía en una celda."],
      tasks: [T.item("powah:furnator_starter"), T.item("powah:energy_cell_starter")],
      rewards: [R.skill(900), R.item("powah:energizing_orb")] },
    { k: "powah2", t: "Batería Powah", sub: "Almacenar", deps: ["powah1"],
      d: ["Una celda de energía básica almacena mucho más. Mejora todo tu sistema con celdas mayores."],
      tasks: [T.item("powah:energy_cell_basic")], rewards: [R.skill(900)] },

    { k: "mek1", t: "Mekanism: primeras máquinas", sub: "Procesamiento", deps: ["alternador"],
      d: ["Mekanism tiene máquinas que multiplican tus minerales: un mineral procesado en una cámara de enriquecimiento da más lingotes.",
          "Empieza con circuitos de control básicos."],
      tasks: [T.item("mekanism:enrichment_chamber"), T.item("mekanism:basic_control_circuit", 4)],
      rewards: [R.skill(1000), R.item("mekanism:basic_universal_cable", 8)] },
    { k: "mek2", t: "Osmio", sub: "El metal de Mekanism", deps: ["mek1"],
      d: ["El osmio es la base de Mekanism. Mínalo en cuevas y fúndelo."],
      tasks: [T.item("mekanism:ingot_osmium", 16)], rewards: [R.skill(1000), R.job("minero", 200)] },
    { k: "mek3", t: "Acero", sub: "Infusión", deps: ["mek2"],
      d: ["El infusor metalúrgico mezcla materiales; con él fabricas acero y aleaciones de infusión."],
      tasks: [T.item("mekanism:metallurgic_infuser"), T.item("mekanism:ingot_steel", 8)],
      rewards: [R.skill(1100), R.item("mekanism:steel_casing")] },
    { k: "mek4", t: "Triple procesado", sub: "Multiplica tus minerales", deps: ["mek3"],
      d: ["Con trituradora y cámara de purificación, cada mineral da varias veces más lingotes."],
      tasks: [T.item("mekanism:crusher"), T.item("mekanism:purification_chamber")],
      rewards: [R.skill(1100), R.item("mekanism:advanced_control_circuit", 4)] },
    { k: "mek5", t: "Cubos de energía", sub: "Almacén de energía", deps: ["mek3"],
      d: ["Los cubos de energía guardan grandes cantidades y se conectan con cables universales."],
      tasks: [T.item("mekanism:basic_energy_cube"), T.item("mekanism:basic_universal_cable", 16)],
      rewards: [R.skill(1000)] },
    { k: "robit", t: "Robit (opcional)", sub: "Tu robot personal", deps: ["mek4", "mek5"], opt: true,
      d: ["El robit es un ayudante que recoge objetos y te sigue. Es muy básico, pero divertido."],
      tasks: [T.item("mekanism:robit")], rewards: [R.skill(1200)] },

    { k: "ae1", t: "AE2: cuarzo", sub: "Sistema de almacenamiento", deps: ["energia"],
      d: ["Applied Energistics 2 guarda objetos en una red y los automatiza. Empieza con cuarzo certus: minado en meteoritas y cuevas.",
          "Un cargador convierte cuarzo certus en cuarzo cargado."],
      tasks: [T.item("ae2:certus_quartz_crystal", 8), T.item("ae2:charger")],
      rewards: [R.skill(1000), R.item("ae2:charged_certus_quartz_crystal", 2)] },
    { k: "ae2", t: "Tu primera red", sub: "Controlador y unidades", deps: ["ae1"],
      d: ["Una red de ME necesita energía, un controlador, una unidad de disco y un terminal. Conecta todo con cables."],
      tasks: [T.item("ae2:controller"), T.item("ae2:drive"), T.item("ae2:terminal"), T.item("ae2:item_storage_cell_1k")],
      rewards: [R.skill(1200), R.item("ae2:fluix_glass_cable", 8)] },
    { k: "ae3", t: "Procesadores", sub: "El corazón de AE2", deps: ["ae2"],
      d: ["Los procesadores se fabrican con moldes en un inscriptor. Necesitas lógica, cálculo e ingeniería.",
          "Un mecanismo de precisión de Create viene muy bien en esta etapa."],
      tasks: [T.item("ae2:inscriber"), T.item("ae2:logic_processor", 4), T.item("ae2:calculation_processor", 4), T.item("ae2:engineering_processor", 4)],
      rewards: [R.skill(1300), R.coins({ diamante: 1 })] },
    { k: "ae4", t: "Autocrafteo", sub: "Fabricación automática", deps: ["ae3"],
      d: ["Con un proveedor de patrones, un ensamblador molecular y una unidad de crafteo, tu red fabrica lo que le pidas."],
      tasks: [T.item("ae2:pattern_provider"), T.item("ae2:molecular_assembler"), T.item("ae2:crafting_unit"), T.item("ae2:pattern_encoding_terminal")],
      rewards: [R.skill(1400), R.coins({ diamante: 2 })] },

    // marcador: reutiliza la línea de producción de Create como requisito de AE2
    { k: "produccion_create", t: "Recuerda: mecanismos de precisión", sub: "De Create", deps: ["ae2"], opt: true,
      d: ["Los procesadores avanzados se apoyan en componentes de Create. Si no tienes mecanismos de precisión, vuelve al capítulo 4."],
      tasks: [T.item("create:precision_mechanism", 2)], rewards: [R.skill(600)] },

    { k: "cierre", t: "Energía estable, red estable", sub: "Cierre del capítulo", deps: ["powah2", "mek4", "mek5", "ae4"],
      d: ["Tienes energía estable, procesamiento de minerales y una red de almacenamiento con autocrafteo. Entrega un núcleo de teletransporte para completar la era tecnológica.",
          "Se abre el capítulo 6: la magia."],
      tasks: [T.item("mekanism:teleportation_core", 1, { consume: true })],
      rewards: [R.skill(2500), R.stage("era_magia"), R.coins({ diamante: 4 })] },
  ],
};
