import { T, R } from "../../quest-dsl.mjs";

// Capítulo 6 — El despertar de la magia (niveles 50–60, ~16 000 XP repartidos)
export default {
  key: "magia", order: 6, group: "campana", icon: "irons_spellbooks:iron_spell_book",
  title: "6. El despertar de la magia",
  sub: "Escuelas de hechizos, glifos, rituales y el Bosque Crepuscular.",
  quests: [
    { k: "intro", t: "El despertar de la magia", sub: "Dos caminos: Iron's y Ars", deps: ["tecnologia.cierre"],
      d: ["Hay dos magias en este mundo. &6Iron's Spells 'n Spellbooks&r es la magia de combate: escuelas de hechizos que se lanzan con bastones y grimorios.",
          "&6Ars Nouveau&r es la magia de rituales, glifos y utilidades. Las dos se complementan.",
          "Las escuelas del pack: &6Fuego&r, &6Hielo&r, &6Oscuridad&r (vacío, sangre, ancestral) y &6Arcana&r (evocación y sagrado). Necesitas Mago para lanzar hechizos."],
      tasks: [T.check()], rewards: [R.skill(1000), R.coins({ diamante: 2 })] },

    // ---- Iron's Spells ----
    { k: "esencia", t: "Esencia arcana", sub: "El material de la magia", deps: ["intro"],
      d: ["La esencia arcana se obtiene de enemigos mágicos y estructuras. Es la base de casi todo en Iron's Spells."],
      tasks: [T.item("irons_spellbooks:arcane_essence", 8)],
      rewards: [R.skill(1100), R.item("irons_spellbooks:common_ink", 8)] },
    { k: "mesa_inscripcion", t: "Mesa de inscripción", sub: "Grimorios y pergaminos", deps: ["esencia"],
      d: ["En la mesa de inscripción puedes inscribir hechizos en un grimorio. Los pergaminos se usan una vez; los hechizos inscritos, siempre."],
      tasks: [T.item("irons_spellbooks:inscription_table"), T.item("irons_spellbooks:common_ink", 4)],
      rewards: [R.skill(1200), R.item("irons_spellbooks:uncommon_ink", 4)] },
    { k: "runas", t: "Runas de escuela", sub: "Una por escuela", deps: ["mesa_inscripcion"],
      d: ["Cada escuela tiene su runa. Con una runa en el yunque arcano mejoras un objeto de esa escuela.",
          "Elige la escuela que más te guste; te acompañará durante toda la campaña."],
      tasks: [T.item("irons_spellbooks:blank_rune", 4), T.item("irons_spellbooks:arcane_ingot", 2)],
      rewards: [R.skill(1200), R.item("irons_spellbooks:fire_rune"), R.item("irons_spellbooks:ice_rune")] },
    { k: "yunque_arcano", t: "Yunque arcano", sub: "Mejora y separa", deps: ["runas"],
      d: ["El yunque arcano mejora tus objetos mágicos y también sirve para destruirlos y recuperar materiales."],
      tasks: [T.item("irons_spellbooks:arcane_anvil")], rewards: [R.skill(1300)] },
    { k: "grimorio", t: "Tu grimorio", sub: "Requiere Mago (Tier I o II)", deps: ["mesa_inscripcion"],
      d: ["Un grimorio de oro o diamante guarda más hechizos. Cuando tengas el nodo &6Mago Tier II&r (Fundamentos VI) podrás usarlo."],
      tasks: [T.item("irons_spellbooks:gold_spell_book")],
      rewards: [R.skill(1300), R.item("irons_spellbooks:mana_ring")] },
    { k: "armadura_magica", t: "Armadura de mago", sub: "Piromante, criomante...", deps: ["grimorio"], opt: true,
      d: ["Las armaduras de mago dan poder de escuela y maná. Requieren Mago (Tier II)."],
      tasks: [T.item("irons_spellbooks:pyromancer_chestplate")],
      rewards: [R.skill(1200)] },
    { k: "elige_escuela", t: "Elige tu escuela", sub: "Especialízate", deps: ["grimorio", "runas"],
      d: ["Gasta tus puntos en un camino del árbol de habilidades: Piromancia, Criomancia, Arcanismo u Oscuridad. Cada uno mejora la escuela correspondiente."],
      tasks: [T.stage("maestria_mago_2")],
      rewards: [R.skill(1500)] },

    // ---- Ars Nouveau ----
    { k: "gema", t: "Gemas de fuente", sub: "Ars Nouveau", deps: ["intro"],
      d: ["La fuente es la energía mágica de Ars Nouveau. Las gemas se consiguen de la magia del entorno y se procesan en la mesa de escritura."],
      tasks: [T.item("ars_nouveau:source_gem", 8), T.item("ars_nouveau:magebloom", 8)],
      rewards: [R.skill(1100), R.item("ars_nouveau:magebloom_fiber", 8)] },
    { k: "libro", t: "Libro de hechizos de Ars", sub: "Novato", deps: ["gema"],
      d: ["Con el libro de hechizos creas tus propios hechizos combinando glifos. Cambias de hechizo con las teclas configuradas."],
      tasks: [T.item("ars_nouveau:novice_spell_book")],
      rewards: [R.skill(1200), R.item("ars_nouveau:wand")] },
    { k: "escribas", t: "Mesa de escriba", sub: "Glifos", deps: ["libro"],
      d: ["La mesa de escriba te permite crear glifos con gemas de fuente. Empieza por los básicos: proyectil, impacto, curar."],
      tasks: [T.item("ars_nouveau:scribes_table")], rewards: [R.skill(1300)] },
    { k: "jarra_fuente", t: "Jarra de fuente", sub: "Almacenar energía", deps: ["escribas"],
      d: ["Una jarra de fuente almacena fuente para alimentar aparatos y rituales. Se rellena con enlaces de fuente."],
      tasks: [T.item("ars_nouveau:source_jar")], rewards: [R.skill(1300)] },
    { k: "aparato", t: "Aparato de encantamiento", sub: "Objetos mágicos", deps: ["jarra_fuente"],
      d: ["Con el aparato de encantamiento y pedestales arcanos creas objetos mágicos poderosos y mejoras tu equipo."],
      tasks: [T.item("ars_nouveau:enchanting_apparatus"), T.item("ars_nouveau:arcane_pedestal", 4)],
      rewards: [R.skill(1500), R.item("ars_nouveau:arcane_core")] },
    { k: "brasero", t: "Rituales", sub: "Magia poderosa", deps: ["aparato"],
      d: ["El brasero ritual hace magia colectiva: cambia el clima, hace crecer bosques o invoca criaturas. Lo primero: fabricar el brasero."],
      tasks: [T.item("ars_nouveau:ritual_brazier")], rewards: [R.skill(1500)] },
    { k: "familiar", t: "Familiar (opcional)", sub: "Un compañero mágico", deps: ["brasero"], opt: true,
      d: ["Un familiar te acompaña y te da pequeñas bonificaciones. El starbuncle es el más popular."],
      tasks: [T.item("ars_nouveau:starbuncle_charm")], rewards: [R.skill(1200)] },

    // ---- Bosque Crepuscular ----
    { k: "crepusculo", t: "El Bosque Crepuscular", sub: "Una dimensión nueva", deps: ["elige_escuela", "brasero"],
      d: ["Arrojando un diamante a un estanque rodeado de flores se abre un portal al Bosque Crepuscular.",
          "Es una dimensión llena de estructuras, jefes y materiales propios. Prepara buena armadura y comida."],
      tasks: [T.adv("twilightforest:root")], rewards: [R.skill(1800), R.coins({ diamante: 2 })] },
    { k: "naga", t: "La Naga", sub: "Primer jefe", deps: ["crepusculo"],
      d: ["El Patio de la Naga guarda a la primera jefa del bosque. Derrótala para conseguir sus escamas y avanzar."],
      tasks: [T.adv("twilightforest:progress_naga")],
      rewards: [R.skill(2500), R.coins({ diamante: 2 })] },
    { k: "lich", t: "La torre del Lich", sub: "Segundo jefe", deps: ["naga"],
      d: ["Tras la Naga aguarda el Lich en su torre. Es un jefe de magia: prepara resistencia mágica y armas de distancia."],
      tasks: [T.adv("twilightforest:progress_lich")],
      rewards: [R.skill(3000), R.coins({ netherita: 1 })] },

    { k: "cierre", t: "Maestro de la magia", sub: "Cierre del capítulo", deps: ["naga", "elige_escuela", "brasero"],
      d: ["Has dominado la magia básica y vencido a la Naga. El mundo te espera.", "Se abre el capítulo 7."],
      tasks: [T.item("ars_nouveau:source_gem", 16, { consume: true })],
      rewards: [R.skill(3500), R.stage("era_7"), R.coins({ netherita: 1 })] },
  ],
};
